spring:
  application:
    name: Config-Default
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka server URL
    register-with-eureka: true   # Register this service with Eureka
    fetch-registry: true         # Fetch registry from Eureka
  instance:
    prefer-ip-address: true       # Prefer IP
